import Head from 'next/head'
import Script from 'next/script';
import { useEffect } from 'react';
import Search from '../components/Search';
import Tag from '../components/Tag';
export default function Home() {

  useEffect(() => {

    setTimeout(() => {
      let coll = document.getElementsByTagName('div')
      for (let i = 0; i < coll.length; i++) {
        if (coll[i].style.width === '100%') coll[i].style.display = 'none';
      }
    }, 2500)
  }, [])

  return (
    <>
      <Head>
        <title>NASDAQ | home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <Script
          src='https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2718245060461029'
          crossOrigin="anonymous"
        />
      </Head>
      <header className="w3-container w3-center w3-padding-48 w3-white">
        <h1 className="w3-xxxlarge"><b>NASDAQ 100 INDEX</b></h1>
        <h6>Good luck with your <span className="w3-tag">trading!</span></h6>
      </header>
      <header id='home-header'>
        <Script
          id="stockmarketwidget"
          src="https://s3.tradingview.com/external-embedding/embed-widget-hotlists.js"
          onLoad={() => {
            document.getElementById('home-header').appendChild(document.getElementById('stockmarketwidget'));
          }}>
          {JSON.stringify({
            "colorTheme": "light",
            "dateRange": "12M",
            "exchange": "US",
            "showChart": true,
            "locale": "en",
            "width": "100%",
            "height": "500",
            "largeChartUrl": "",
            "isTransparent": false,
            "showSymbolLogo": false,
            "showFloatingTooltip": false,
            "plotLineColorGrowing": "rgba(41, 98, 255, 1)",
            "plotLineColorFalling": "rgba(255, 0, 0, 1)",
            "gridLineColor": "rgba(42, 46, 57, 0)",
            "scaleFontColor": "rgba(106, 109, 120, 1)",
            "belowLineFillColorGrowing": "rgba(41, 98, 255, 0.12)",
            "belowLineFillColorFalling": "rgba(41, 98, 255, 0.12)",
            "belowLineFillColorGrowingBottom": "rgba(41, 98, 255, 0)",
            "belowLineFillColorFallingBottom": "rgba(41, 98, 255, 0)",
            "symbolActiveColor": "rgba(41, 98, 255, 0.12)"
          })}
        </Script>
      </header>
      <div className="w3-row w3-padding w3-border">
        <div className="w3-col l8 s12">

          <div className='w3-container w3-white'>
            <div className="w3-center">
              <h2>WHAT IS <span className="w3-opacity">NASDAQ 100 INDEX ?</span></h2>
            </div>
            <div className='w3-justify'>
              <img src="/nasdaq.jpg" alt="nasdaq" width={'100%'} className="w3-padding-16" />
              <p>
                The NASDAQ 100 index is a market-capitalization weighted index that consists of 100 of the largest non-financial companies listed on the NASDAQ stock exchange. It is designed to represent the performance of the technology and consumer services sectors, and is considered a leading indicator of the overall performance of the NASDAQ exchange.
              </p>
              <p>
                The NASDAQ 100 index is known for its high volatility and fast-paced trading, and is home to some of the most well-known and influential technology companies in the world, such as Apple, Microsoft, Amazon, and Google. It is widely followed by traders and investors, and is often used as a benchmark for the overall health of the technology sector.
              </p>
              <p>
                The NASDAQ 100 index is calculated using a proprietary methodology that takes into account market capitalization, liquidity, and industry representation. It is updated on a real-time basis, and is widely available through various financial news and data sources, including Bloomberg, Yahoo Finance, and the NASDAQ website.
              </p>
            </div>
          </div>

          <div className='w3-container'>
            <div className="w3-center">
              <h3>ECONOMIC CALENDER</h3>
            </div>
            <div className='w3-justify' id='economic'>
              <Script
                id="economiccalenderwidget"
                src="https://s3.tradingview.com/external-embedding/embed-widget-events.js"
                onLoad={() => {
                  document.getElementById('economic').appendChild(document.getElementById('economiccalenderwidget'));
                }}>
                {JSON.stringify({
                  "width": "100%",
                  "height": "500",
                  "colorTheme": "light",
                  "isTransparent": false,
                  "locale": "en",
                  "importanceFilter": "-1,0,1"
                })}
              </Script>
            </div>
          </div>
        </div>
        <div className='w3-col l4'>

          <div className="w3-white w3-margin">
            <img src="/WKX.gif" alt="WKX.gif" style={{ width: '100%' }} className="w3-grayscale" />
            <div className=" w3-padding w3-black">
              <h4>About</h4>
            </div>
            <p>
              Welcome to NASDAQ APP, the ultimate resource for stock traders and investors looking to stay on top of the NASDAQ 100 index.
              With our app, you can easily track the top five gaining, losing, and most active stocks of the day, as well as access a wealth of information about any stock asset in the index, including symbol info, technical analysis, fundamental data, and company profiles.
              Plus, stay ahead of the game with our real-time updates on upcoming economic events, announcements, and news. NASDAQ APP is your one-stop shop for all things NASDAQ 100 – start using it today and take your trading to the next level!
            </p>
          </div>

          <hr />

          <div className="w3-white w3-margin">
            <div className="w3-container w3-padding w3-black">
              <h4>Search</h4>
            </div>
            <div className="w3-container w3-white">
              <p>Enter components of the nasdaq 100.</p>
              <Search />
            </div>
          </div>

          <hr />

          <div className="w3-white w3-margin">
            <div className="w3-container w3-padding w3-black">
              <h4>Tags</h4>
            </div>
            <div className="w3-container">
              <Tag />
            </div>
          </div>

          <hr />

          <div className="w3-white w3-margin">
            <div className="w3-container w3-padding w3-black">
              <h4>Advertise</h4>
            </div>
            <div className="w3-container w3-white">
              <div className="w3-container w3-display-container w3-light-grey w3-section" style={{ height: '200px' }}>
                <span className="w3-display-middle">Your AD Here</span>
              </div>
            </div>
          </div>

          <hr />



        </div>
      </div>
      <div className='w3-padding'></div>
    </>
  )
}
